[package]
name = "coroutine"
version = "0.1.0"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]

[dependencies]
log = "0.3.6"
time = "0.1.35"
smallvec = "0.2.0"
net2 = { version = "0.2.26", default-features = false }

[dependencies.generator]
path ="../generator-rs"
[dependencies.queue]
path ="../queue"

[target.'cfg(unix)'.dependencies]
bitflags = "0.3"
libc = "0.2.16"
nix = "0.7.0"

[target.'cfg(windows)'.dependencies]
miow = "0.1.3"
winapi = "0.2.8"
kernel32-sys = "0.2"

[profile.release]
opt-level=3
