[package]
name = "coroutine"
version = "0.1.0"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]

[dependencies]
bitflags = "0.3"
smallvec = "0.2.0"
time = "0.1.35"
log    = "0.3.6"
#net2 = { version = "0.2.26", default-features = false }

[dependencies.generator]
path ="../generator-rs"
[dependencies.queue]
path ="../queue"

#[target.'cfg(unix)'.dependencies]
#nix    = "0.7.0"
#libc   = "0.2.16"

[target.'cfg(windows)'.dependencies]
miow = "0.1.3"
winapi = "0.2.8"
kernel32-sys = "0.2"

[profile.release]
opt-level=3
